name: Build Profile Configurator EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: scripts/profileconfigurator
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Profile Configurator EXE
        working-directory: scripts/profileconfigurator
        run: |
          pyinstaller --onefile --noupx --windowed --icon ProfileConfigurator.ico --add-data "ProfileConfigurator.ico;." --version-file version_info.txt --name "ProfileConfigurator" ProfileConfigurator.py

      - uses: actions/upload-artifact@v4
        with:
          name: ProfileConfigurator
          path: scripts/profileconfigurator/dist/ProfileConfigurator.exe